[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
watch = [
    "assets",
    "src",
    "index.html",
    "style.css",
    "Cargo.toml",
    "Cargo.lock",
    "Trunk.toml",
    ".cargo",
]
